services:
  mongo:
    image: mongo:8.0
    container_name: MongoDB-ExpenseTracker
    restart: on-failure
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    volumes:
      - "c:/temp/expenseTracker/db:/data/db"
    ports:
      - "27017:${MONGO_PORT}"
    healthcheck:
      test: ["CMD", "mongo", "--eval", "db.adminCommand('ping')"]
      interval: 20s
      timeout: 10s
      retries: 10


  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: FastAPI-ExpenseTracker
    ports:
      - "8000:8000"
    environment:
      - MONGO_URI=mongodb://${MONGO_INITDB_ROOT_USERNAME}:${MONGO_INITDB_ROOT_PASSWORD}@mongo:${MONGO_PORT}/?authSource=admin
    depends_on:
      mongo:
        condition: service_healthy
    restart: on-failure

volumes:
  mongo_data:

networks:
  default:
    driver: bridge
