services:
  db:
    image: postgres:17.6
    container_name: expense_db
    restart: on-failure
    environment:
      POSTGRES_USER: expense_user
      POSTGRES_PASSWORD: expense_pass
      POSTGRES_DB: expense_tracker
    ports:
      - "5432:5432"
    volumes:
      - "c:/temp/expenseTracker/db:/var/lib/postgresql/data"
    networks:
      - expense_net

networks:
  expense_net:
    driver: bridge